language: node_js

node_js:
  - '6'
  - '8'

notifications:
  email:
    on_success: change
    on_failure: always

# Use container-based Travis infrastructure.
sudo: required
dist: trusty

addons:
  firefox: latest
  chrome: beta

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

jobs:
  include:
    - script: npm run lint
    - script: npm run test:browser
    - script: bash ./scripts/ci/coverage.sh
    - script: npm run test:package
